language: java
addons:
  sonarcloud:
    organization: "sonarcloud-analyzer"
    branches:
    - .*
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
